version: "3.8"
services:
  sensor-service:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - monitoring

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    expose:
      - "8428"
    volumes:
      - video_m_data:/victoria-metrics-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--promscrape.config.strictParse=false"
      - "--storageDataPath=/victoria-metrics-data"
      - "--promscrape.dropOriginalLabels=false"
      - "--retentionPeriod=7d"
    networks:
      - monitoring
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ENABLE_GZIP=true
    networks:
      - monitoring
    restart: always
    deploy:
      resources:
        limits:
          memory: 150M

volumes:
  video_m_data:

networks:
  monitoring:
