global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "victoria_matrix"
    static_configs:
      - targets: ["victoria-metrics:8428"]

  - job_name: "sensor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["sensor-service:8000"]
